# Site settings
title: Y.A Obbi Ikhsan
description: '| Mahasiswa Sistem Informasi | Fakultas Sains dan Teknologi | Universitas Islam Negeri Sultan Syarif Kasim Riau |'
url: 'http://obbi21.github.io'
baseurl: '/obbi21.github.io'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Obbi'
  email: yaobbiikhsan.gmail.com
  twitter_username: https://twitter.com/login?lang=id
  facebook_username: https://web.facebook.com/Bhy.Anareng
  github_username:  https://github.com/obbi21
  linkedin_username:  https://www.linkedin.com/in/y-a-obbi-ikhsan-201486155/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
